name: Test, Lint and Coverage

on:
  push:
    branches: [ '**' ]  # Run on all branches
  pull_request:
    branches: [ main, development ]  # PRs targeting main or development

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2.3'
        bundler-cache: true

    - name: Run tests with coverage
      run: bundle exec rspec

    - name: Run standard linting
      run: bundle exec rake standard

    - name: Check coverage requirements
      run: bundle exec rake coverage:check

    - name: Upload coverage report
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: coverage/
